### ISSUE TITLE
Question: Support for distinguishing build dependencies?

### ISSUE THREAD

**Issue by tofay** [aquasecurity/go-dep-parser#120]
#119 adds supports for Rust dependencies built with cargo-auditable.

cargo-auditable currently injects runtime and build dependencies, and #119 only extracts the former. Should go-dep-parser also extract the latter, and if so should it also indicate that they are build dependencies somehow?

(Looking at the poetry and cargo lockfile detectors, it looks like there isn't a disambiguation, so I think I can just remove the runtime filtering in the rust binary parser?)

**Comment by knqyf263** [comment]
>cargo-auditable currently injects runtime and build dependencies, and https://github.com/aquasecurity/go-dep-parser/pull/119 only extracts the latter.

You mean the former, not latter, right?

>Should go-dep-parser also extract the latter, and if so should it also indicate that they are build dependencies somehow?

I'm not sure if we should extract build dependencies as well since it is not included in binary. If you scan Cargo.lock, it makes sense to show build dependencies.

**Comment by tofay** [comment]
> You mean the former, not latter, right?

Yes, apologies. I've updated the OP

**Comment by knqyf263** [comment]
Let's see how it goes for the community. I think it is reasonable to show only runtime dependencies when scanning Rust binaries.
