### ISSUE TITLE
indirect dependencies of npm package-lock.json with lockfileversion=3 are not detected

### ISSUE THREAD

**Issue by danielciuraru86** [aquasecurity/go-dep-parser#170]
package-lock.json generated with lockfileversion=3 does not include the dependencies array (its deprecated https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion). 

Current node LTS is 18 which uses lockfileversion=3 hence features that depend on the dependencies array being present will not work since the dependencies are not picked up.

The issue seems to be here:
https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/nodejs/npm/parse.go#L57

The indirect dependencies should be taken from packages field.

**Comment by knqyf263** [comment]
Hopefully, https://github.com/aquasecurity/go-dep-parser/pull/196 addressed this issue.
