### ISSUE TITLE
Add direct parent field to NPM dep tree

### ISSUE THREAD

**Issue by guyb1** [aquasecurity/go-dep-parser#188]
In addition to the 'DependsOn' field of the 'Dependency' struct, we want to have another field called "DirectParents".
It will contain the direct parents of the library (could be more than one).
That will give us the ability to locate the root library from the child dependency.

[PR](https://github.com/aquasecurity/go-dep-parser/pull/183)

**Comment by knqyf263** [comment]
>It will contain the direct parents of the library (could be more than one).

Why do you need it? You can create parents from `DependsOn` by reversing them. Is `DirectParents` different from that?
