### ISSUE TITLE
Removal of golang.org/x/xerrors

### ISSUE THREAD

**Issue by mmorel-35** [aquasecurity/go-dep-parser#58]
golang.org/x/x errors can be replaced by "errors" or "fmt" modules
Quoted from https://pkg.go.dev/golang.org/x/xerrors#pkg-overview
>These functions were incorporated into the standard library's errors package in Go 1.13: - Is - As - Unwrap
Also, Errorf's %w verb was incorporated into fmt.Errorf.
Use this package to get equivalent behavior in all supported Go versions.

**Comment by knqyf263** [comment]
No, it doesn't support stacktrace yet. We have to wait for Go 2.
https://go.googlesource.com/proposal/+/master/design/29934-error-values.md

**Comment by mmorel-35** [comment]
Good to know, great share :) !
