### ISSUE TITLE
`go-dep-parser` handles incorrectly a package name with a hyphen

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/go-dep-parser#81]
there is a problem if a package name contains a hyphen.

`go-dep-parser` doesn't detect next packages for python:
```
oauth2-client==4.0.0
python-gitlab==2.0.0
```
Reason:
`rStripByKey(line, hashMarker)`  cuts incorrectly such names.

https://github.com/aquasecurity/go-dep-parser/blob/4a30ebc4b509209c8e61561930cd760c28a8201d/pkg/python/pip/parse.go#L44-L49

**Comment by afdesk** [comment]
I can create a PR for fix this issue.
@knqyf263 is it ok?

**Comment by knqyf263** [comment]
yes, please
